// Reference "encyclopedia" content for each ETL operator — powers the rich
// operator inspector (definition, pros/cons, ratings, code). Teaching metadata
// only; the actual transforms run in etlUtils.ts.
import type { OpType } from "@/lib/etlUtils";

export type OpCategory = "transformation" | "integration";

export interface OpInfo {
  category: OpCategory;
  definition: string;
  purpose: string;
  advantages: string[];
  disadvantages: string[];
  speed: "Very fast" | "Fast" | "Medium" | "Slow";
  memory: "Low" | "Medium" | "High";
  scalability: "Low" | "Medium" | "High";
  cost: "Low" | "Medium" | "High";
  pandas: string;
  spark: string;
}

export const OP_CATEGORY_COLOR: Record<OpCategory, string> = {
  transformation: "#a855f7",
  integration: "#14b8a6",
};

export const OP_INFO: Record<OpType, OpInfo> = {
  filter: { category: "transformation", definition: "Keep only the rows that match a condition (SQL WHERE).", purpose: "Remove irrelevant records early so every later stage does less work.", advantages: ["Reduces volume", "Very fast", "Simple logic"], disadvantages: ["Can drop needed rows", "Needs clear rules"], speed: "Very fast", memory: "Low", scalability: "High", cost: "Low", pandas: `df = df[df["amount"] > 0]`, spark: `df = df.filter(F.col("amount") > 0)` },
  select: { category: "transformation", definition: "Project a subset of columns, dropping the rest.", purpose: "Narrow the schema to only the fields downstream stages need.", advantages: ["Smaller rows", "Clearer schema", "Faster shuffles"], disadvantages: ["Drops columns permanently", "Easy to omit a field"], speed: "Very fast", memory: "Low", scalability: "High", cost: "Low", pandas: `df = df[["id", "region", "amount"]]`, spark: `df = df.select("id", "region", "amount")` },
  derive: { category: "transformation", definition: "Add a computed column from two existing fields.", purpose: "Create new features (ratios, totals) without leaving the pipeline.", advantages: ["Feature engineering", "Reusable downstream", "Cheap"], disadvantages: ["Nulls on bad input", "Formula must be valid"], speed: "Fast", memory: "Low", scalability: "High", cost: "Low", pandas: `df["total"] = df["price"] * df["qty"]`, spark: `df = df.withColumn("total", F.col("price") * F.col("qty"))` },
  aggregate: { category: "transformation", definition: "Group rows by a column and summarize (sum, avg, count…).", purpose: "Collapse detail into metrics for reporting and dashboards.", advantages: ["Compact output", "Fast analytics", "Reduces rows"], disadvantages: ["Loses row detail", "Skew on hot keys"], speed: "Fast", memory: "Medium", scalability: "High", cost: "Low", pandas: `agg = df.groupby("region")["amount"].sum()`, spark: `agg = df.groupBy("region").agg(F.sum("amount"))` },
  sort: { category: "transformation", definition: "Order rows by one column, ascending or descending.", purpose: "Prepare data for ranking, top-N, or readable display.", advantages: ["Enables ranking", "Improves readability", "Aids merge joins"], disadvantages: ["Expensive on large data", "Memory heavy"], speed: "Medium", memory: "High", scalability: "Medium", cost: "Low", pandas: `df = df.sort_values("amount", ascending=False)`, spark: `df = df.orderBy(F.col("amount").desc())` },
  dedupe: { category: "transformation", definition: "Remove duplicate rows (whole-row or by key columns).", purpose: "Guarantee uniqueness before joins, counts, or loads.", advantages: ["Improves quality", "Prevents double counting", "Reduces storage"], disadvantages: ["Can be slow", "Needs stable keys"], speed: "Medium", memory: "Medium", scalability: "High", cost: "Low", pandas: `df = df.drop_duplicates(subset=["email"])`, spark: `df = df.dropDuplicates(["email"])` },
  clean: { category: "transformation", definition: "Handle nulls by dropping rows or filling them with 0.", purpose: "Produce a clean frame that won't error later or bias analytics.", advantages: ["Fewer errors", "Cleaner analytics", "Fast"], disadvantages: ["Dropping loses data", "Filling can bias"], speed: "Very fast", memory: "Low", scalability: "High", cost: "Low", pandas: `df = df.dropna()   # or df.fillna(0)`, spark: `df = df.dropna()   # or df.fillna(0)` },
  rename: { category: "transformation", definition: "Change a column's name for consistency.", purpose: "Align schemas across sources so joins and loads line up.", advantages: ["Consistency", "Easier joins", "Clear semantics"], disadvantages: ["Breaks downstream refs", "Tedious in bulk"], speed: "Very fast", memory: "Low", scalability: "High", cost: "Low", pandas: `df = df.rename(columns={"Name": "name"})`, spark: `df = df.withColumnRenamed("Name", "name")` },
  limit: { category: "transformation", definition: "Keep only the first N rows.", purpose: "Sample the head for a fast preview or a capped export.", advantages: ["Instant preview", "Bounds cost", "Simple"], disadvantages: ["Not a random sample", "Order dependent"], speed: "Very fast", memory: "Low", scalability: "High", cost: "Low", pandas: `df = df.head(10)`, spark: `df = df.limit(10)` },
  sample: { category: "transformation", definition: "Randomly sample a fraction (≤1) or a count of rows.", purpose: "Work on a representative subset when the full set is too big.", advantages: ["Representative", "Cheap to iterate", "Reduces skew vs head"], disadvantages: ["Non-deterministic", "Small samples miss rare cases"], speed: "Fast", memory: "Low", scalability: "High", cost: "Low", pandas: `df = df.sample(frac=0.5)`, spark: `df = df.sample(0.5)` },
  map: { category: "transformation", definition: "Apply a function to one column (upper, round, trim, length…).", purpose: "Normalize or reshape values with a per-column transform.", advantages: ["Flexible", "Expressive", "Reusable"], disadvantages: ["Slow if not vectorized", "Hard to optimize"], speed: "Medium", memory: "Low", scalability: "Medium", cost: "Low", pandas: `df["name"] = df["name"].str.upper()`, spark: `df = df.withColumn("name", F.upper(F.col("name")))` },
  fillna: { category: "transformation", definition: "Replace nulls in a column with a specific value.", purpose: "Impute missing values so metrics don't silently skip rows.", advantages: ["Keeps rows", "Stable metrics", "Targeted"], disadvantages: ["Imputation biases", "Wrong default hides gaps"], speed: "Very fast", memory: "Low", scalability: "High", cost: "Low", pandas: `df["rev"] = df["rev"].fillna(0)`, spark: `df = df.fillna(0, subset=["rev"])` },
  bucket: { category: "transformation", definition: "Bin a numeric column into N equal-width buckets.", purpose: "Turn a continuous value into categories for grouping or ML.", advantages: ["Enables grouping", "Handles outliers", "ML friendly"], disadvantages: ["Loses precision", "Bin count is a judgement call"], speed: "Fast", memory: "Low", scalability: "High", cost: "Low", pandas: `df["bin"] = pd.cut(df["amount"], 4, labels=False)`, spark: `# min-max scale × N, cast to int` },
  join: { category: "integration", definition: "Combine two datasets on a shared key.", purpose: "Enrich each row with related attributes from Source B.", advantages: ["Rich single view", "Enables analytics", "Flexible keys"], disadvantages: ["Expensive", "Fan-out risk", "Needs indexes"], speed: "Medium", memory: "High", scalability: "Medium", cost: "Medium", pandas: `df = df.merge(dfB, on="id", how="inner")`, spark: `df = df.join(dfB, df["id"] == dfB["id"], "inner")` },
  union: { category: "integration", definition: "Stack Source B's rows under this table (same schema).", purpose: "Append rows from multiple sources into one set.", advantages: ["Simple","Fast","Scales horizontally"], disadvantages: ["Schemas must match","Duplicates unless distinct"], speed: "Fast", memory: "Low", scalability: "High", cost: "Low", pandas: `df = pd.concat([df, dfB])`, spark: `df = df.unionByName(dfB, allowMissingColumns=True)` },
  lookup: { category: "integration", definition: "Enrich each row by looking up matching record from a secondary table (left join).", purpose: "Add supplemental columns from a reference table without duplicating rows.", advantages: ["Adds reference data","No row duplication"], disadvantages: ["Requires key match","May add many columns"], speed: "Medium", memory: "Medium", scalability: "Medium", cost: "Low", pandas: `df = df.merge(dfB, left_on='key', right_on='ref_key', how='left')`, spark: `df = df.join(dfB, df["key"] == dfB["ref_key"], "left")` },
  merge: { category: "integration", definition: "Update rows with matching keys by merging fields from secondary table.", purpose: "Refresh or supplement existing records based on a key.", advantages: ["In-place update","Preserves primary rows"], disadvantages: ["Overwrites data","Requires unique keys"], speed: "Medium", memory: "Medium", scalability: "Medium", cost: "Low", pandas: `df.update(dfB.set_index('key'), overwrite=True)`, spark: `df = df.alias('a').join(dfB.alias('b'), "a.key = b.key", "left").selectExpr('a.*', 'b.*')` },
  append: { category: "integration", definition: "Append rows from a secondary table, aligning columns by name.", purpose: "Combine datasets with possibly differing schemas.", advantages: ["Simple concatenation","Handles schema differences"], disadvantages: ["May produce many nulls","No deduplication"], speed: "Fast", memory: "Low", scalability: "High", cost: "Low", pandas: `df = pd.concat([df, dfB], ignore_index=True)`, spark: `df = df.unionByName(dfB, allowMissingColumns=True)` },
  pivot: { category: "transformation", definition: "Spread one column's values into new columns (long → wide).", purpose: "Reshape into a matrix for reporting or feature tables.", advantages: ["Report-ready shape", "One row per group", "Readable"], disadvantages: ["Explodes columns", "Sparse if high cardinality"], speed: "Medium", memory: "Medium", scalability: "Medium", cost: "Low", pandas: `df = df.pivot_table(index="region", columns="status", values="amount", aggfunc="sum")`, spark: `df = df.groupBy("region").pivot("status").agg(F.sum("amount"))` },
  unpivot: { category: "transformation", definition: "Melt several columns into variable/value rows (wide → long).", purpose: "Normalize a wide matrix back into tidy tall records.", advantages: ["Tidy format", "Easier to aggregate", "Chart friendly"], disadvantages: ["More rows", "Loses wide readability"], speed: "Medium", memory: "Medium", scalability: "Medium", cost: "Low", pandas: `df = df.melt(id_vars=["id"], var_name="variable", value_name="value")`, spark: `df = df.unpivot(["id"], ["q1", "q2"], "variable", "value")` },
  window: { category: "transformation", definition: "Compute over a window: running total, rank, row number, lag, lead.", purpose: "Add order-aware columns without collapsing the rows.", advantages: ["Keeps detail", "Powerful analytics", "Order-aware"], disadvantages: ["Needs an order/partition", "Can be expensive"], speed: "Medium", memory: "Medium", scalability: "Medium", cost: "Medium", pandas: `df["running"] = df["amount"].cumsum()`, spark: `df = df.withColumn("running", F.sum("amount").over(w))` },
  regex: { category: "transformation", definition: "Extract the first match/group of a pattern into a new column.", purpose: "Pull structured fields out of messy text (IDs, codes, units).", advantages: ["Parses messy text", "No extra column needed", "Precise"], disadvantages: ["Patterns are brittle", "Empty on no match"], speed: "Medium", memory: "Low", scalability: "High", cost: "Low", pandas: `df["code"] = df["sku"].str.extract(r"(\\d+)")`, spark: `df = df.withColumn("code", F.regexp_extract("sku", r"(\\d+)", 1))` },
  dateparse: { category: "transformation", definition: "Pull year/month/day/weekday or days-since from a date column.", purpose: "Turn a raw date into features for grouping and time analysis.", advantages: ["Enables time analysis", "Group by period", "ML features"], disadvantages: ["Fails on bad formats", "Timezone pitfalls"], speed: "Fast", memory: "Low", scalability: "High", cost: "Low", pandas: `df["year"] = pd.to_datetime(df["date"]).dt.year`, spark: `df = df.withColumn("year", F.year(F.to_date("date")))` },
  scd2: { category: "transformation", definition: "Track dimension changes over time with effective dates and current flags.", purpose: "Maintain complete audit history for changing attributes (Slowly Changing Dimension Type 2).", advantages: ["Full historical audit", "SCD2 standard", "Point-in-time querying"], disadvantages: ["Increases row count", "Requires surrogate keying"], speed: "Medium", memory: "Medium", scalability: "Medium", cost: "Medium", pandas: `df["effective_start"] = "2024-01-01"\ndf["is_current"] = 1`, spark: `df.withColumn("is_current", F.lit(1))` },
  fuzzydedupe: { category: "transformation", definition: "Deduplicate text rows based on string similarity (Levenshtein distance).", purpose: "Group and remove near-duplicate values (e.g. typos, minor spelling variations).", advantages: ["Handles typos", "Data quality improvement", "Flexible threshold"], disadvantages: ["O(N^2) comparison cost", "Potential false matches"], speed: "Slow", memory: "Medium", scalability: "Low", cost: "Medium", pandas: `from fuzzywuzzy import process\n# deduplicate near strings`, spark: `# Use GraphFrames or MinHash LSH` },
  quality: { category: "transformation", definition: "Validate rows against rules (not_null, positive, regex) and flag or quarantine.", purpose: "Ensure incoming data quality meets enterprise standards before load.", advantages: ["Data assurance", "Explicit audit field", "Prevents dirty data"], disadvantages: ["Flags valid edge cases", "Requires rule setup"], speed: "Fast", memory: "Low", scalability: "High", cost: "Low", pandas: `df["_quality_status"] = np.where(df["col"].notnull(), "VALID", "REJECT")`, spark: `df.withColumn("_quality_status", F.when(F.col("col").isNotNull(), "VALID").otherwise("REJECT"))` },
};

// ── source reference (Extract step), keyed by the source tab ──
export interface SourceInfo { label: string; color: string; definition: string; advantages: string[]; disadvantages: string[]; code: string; }
export const SRC_INFO: Record<"sample" | "upload" | "json" | "db", SourceInfo> = {
  sample: { label: "Sample dataset", color: "#3b82f6", definition: "Built-in demo tables (orders, customers…) parsed from CSV — instant, no setup.", advantages: ["Zero setup", "Deterministic", "Good for learning"], disadvantages: ["Not your real data", "Fixed schema"], code: `df = pd.read_csv("orders.csv")` },
  upload: { label: "File upload", color: "#eab308", definition: "CSV / TSV / Excel / JSON parsed locally in the browser (Excel via the server extractor).", advantages: ["Universal formats", "Parsed in-browser", "No connection needed"], disadvantages: ["Large files slow", "CSV has no types"], code: `df = pd.read_csv("your_file.csv")` },
  json: { label: "Pasted JSON", color: "#f97316", definition: "An array of objects (or { data: [...] }) turned into rows — handy for API payloads.", advantages: ["Flexible schema", "Great for API data", "Nested-friendly"], disadvantages: ["Verbose", "No schema enforcement"], code: `df = pd.DataFrame(json.loads(text))` },
  db: { label: "Database query", color: "#06b6d4", definition: "Run SQL against a MySQL / TiDB connection and extract the result set as rows.", advantages: ["Live data", "Push filters to the DB", "Any SQL"], disadvantages: ["Needs credentials", "Network dependent"], code: `df = pd.read_sql("SELECT * FROM orders LIMIT 500", conn)` },
};

// ── destination reference (Load step), keyed by the store target ──
export const LOAD_INFO: Record<"platform" | "external", SourceInfo> = {
  platform: { label: "Platform database", color: "#10b981", definition: "The workbench's own store — one click, no credentials. Good for sharing snapshots in-app.", advantages: ["Instant", "No setup", "Shareable in-app"], disadvantages: ["Lives inside the platform", "Not your production DB"], code: `df.to_sql("dataset", workbench_engine, if_exists="replace")` },
  external: { label: "External MySQL / TiDB", color: "#38bdf8", definition: "Loads into a real database you control — creates the table if missing, then appends or upserts.", advantages: ["Your real DB", "Append or upsert", "Column-type control"], disadvantages: ["Needs credentials", "Schema-drift risk"], code: `df.to_sql("etl_output", create_engine(url), if_exists="append")` },
};
